import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food Network App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Header />
        <div className="flex">
          <div className="hidden lg:block">
            <Navbar />
          </div>
          <div className="bg-[#EEF0F2] w-full lg:rounded-tl-3xl p-3">
            {children}
          </div>
        </div>
        <div className="lg:hidden fixed bottom-0 w-full z-10 bg-white">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
