import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}>
        <Header />
        <div className="flex">
          <Sidebar />
          <div className="bg-[#EEF0F2] w-full rounded-tl-3xl p-3">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
